force-app/main/default/objects/Kerridge_Order__c/Kerridge_Order__c.object-meta.xml
<CustomObject>
    <label>Kerridge Order</label>
    <nameField>
        <label>Kerridge Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kerridge Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kerridge_Order__c/fields/Amount_on_Order__c.field-meta.xml
<CustomField>
    <fullName>Amount_on_Order__c</fullName>
    <label>Amount on Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Kerridge_Order__c/fields/Kerridge_Order__c.field-meta.xml
<CustomField>
    <fullName>Kerridge_Order__c</fullName>
    <externalId>true</externalId>
    <label>Kerridge Order #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Kerridge_Order__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityId</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Kerridge Orders</relationshipLabel>
    <relationshipName>Kerridge_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount_on_Order__c.field-meta.xml
<CustomField>
    <fullName>Amount_on_Order__c</fullName>
    <label>Amount on Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/KerridgeOrderTriggerHelper.cls
public class KerridgeOrderTriggerHelper {
    
    public static void updateOpportuntity(List<Kerridge_Order__c> kerridgeOrder){
        Map<Id,Opportunity> mapOfOpportunityById=new Map<Id,Opportunity>();
        set<Id> opportuntityIds=new set<Id>();
        for(Kerridge_Order__c ko:kerridgeOrder){
            if(ko.OpportunityId__c !=null){
                opportuntityIds.add(ko.OpportunityId__c); 
            }
        }
       List<Kerridge_Order__c> listofKerridgeOrders=[Select Id,OpportunityId__c,Amount_on_Order__c from Kerridge_Order__c where OpportunityId__c IN: opportuntityIds];
        for(Kerridge_Order__c kOrder:listofKerridgeOrders){
            Opportunity op=new Opportunity();
            op.Id=kOrder.OpportunityId__c;
            op.Amount_on_Order__c=kOrder.Amount_on_Order__c;
            mapOfOpportunityById.put(op.Id,op);
        }
        if(!mapOfOpportunityById.isEmpty()){
            update mapOfOpportunityById.values();
        }
    }

}