force-app/main/default/objects/Credit_Application_Form__c/Credit_Application_Form__c.object-meta.xml
<CustomObject>
    <label>Credit Application Form</label>
    <nameField>
        <displayFormat>Credit Form-{000}</displayFormat>
        <label>Credit Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Applications Form</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Application_Form__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Submit For Approval</fullName>
            </value>
            <value>
                <fullName>Sent To Customer</fullName>
            </value>
            <value>
                <fullName>Opened By Customer</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Client Not Interested</fullName>
            </value>
            <value>
                <fullName>Assigned AR Specialist</fullName>
            </value>
            <value>
                <fullName>AR Review Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Credit Applications Form</relationshipLabel>
    <relationshipName>Credit_Applications_Form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreditApplicationFormControllerTest.cls
@isTest
public class CreditApplicationFormControllerTest {

    @isTest
    public static void sendVerificationCodeEmailTest(){
        Contact con = TestDataFactory.getContactInstance();
        insert con;
        Test.startTest();
        String verificationCode = CreditApplicationFormController.generateVerificationCode();
        CreditApplicationFormController.sendEmail(con, verificationCode);
        CreditApplicationFormController.sendVerificationCodeEmail(con.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void getIsSubmittedValueTest(){       
         Contact con = TestDataFactory.getContactInstance();
        insert con;
        Test.startTest();
        Credit_Application_Form__c creditAppFormObj = TestDataFactory.getCreditAppFormInstance();
        creditAppFormObj.Contact__c = con.Id;
        creditAppFormObj.Application_Status__c = CreditApplicationContstants.Application_Status_Sent_To_Customer;
        insert creditAppFormObj;
        
        CreditApplicationFormController.getIsSubmittedValue(con.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void getIsSubmittedValueTest2(){       
         Contact con = TestDataFactory.getContactInstance();
        insert con;
        Test.startTest();
        Credit_Application_Form__c creditAppFormObj = TestDataFactory.getCreditAppFormInstance();
        creditAppFormObj.Contact__c = con.Id;
        creditAppFormObj.Application_Status__c = CreditApplicationContstants.Application_In_Progress;
        insert creditAppFormObj;
        
        CreditApplicationFormController.getIsSubmittedValue(con.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void getIsSubmittedValueTest3(){       
         Contact con = TestDataFactory.getContactInstance();
        insert con;
        Test.startTest();
        Credit_Application_Form__c creditAppFormObj = TestDataFactory.getCreditAppFormInstance();
        creditAppFormObj.Contact__c = con.Id;
        creditAppFormObj.Application_Status__c = CreditApplicationContstants.Application_Status_In_Review;
        insert creditAppFormObj;
        
        CreditApplicationFormController.getIsSubmittedValue(con.Id);
        Test.stopTest();
    }
    @isTest
    public static void getCreditApplicationsTest2(){
        Contact con = TestDataFactory.getContactInstance();
        insert con;
        
        Test.startTest();
        CreditApplicationFormController.getCreditAppValue(con.Id);
        Test.stopTest();
    }
   
}