force-app/main/default/objects/Account/fields/Account_Category__c.field-meta.xml
<CustomField>
    <fullName>Account_Category__c</fullName>
    <label>Account Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Bucket &amp; Trowel</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Commercial Contractor</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Interior Design</fullName>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath</fullName>
            </value>
            <value>
                <fullName>LVT</fullName>
            </value>
            <value>
                <fullName>National Account</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Property Owner</fullName>
            </value>
            <value>
                <fullName>Residential Contractor</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Tile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <inlineHelpText>Which LTD Branch is this account associated with?</inlineHelpText>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central Warehouse 038</fullName>
            </value>
            <value>
                <fullName>Chattanooga 035</fullName>
            </value>
            <value>
                <fullName>Cincinnati 065</fullName>
            </value>
            <value>
                <fullName>Elk Grove Village 085</fullName>
            </value>
            <value>
                <fullName>Evansville 050</fullName>
            </value>
            <value>
                <fullName>Fishers 055</fullName>
            </value>
            <value>
                <fullName>Fort Wayne 070</fullName>
            </value>
            <value>
                <fullName>Grand Rapids 080</fullName>
            </value>
            <value>
                <fullName>Johnson City 033</fullName>
            </value>
            <value>
                <fullName>Knoxville 037</fullName>
            </value>
            <value>
                <fullName>Lexington 060</fullName>
            </value>
            <value>
                <fullName>Louisville 040</fullName>
            </value>
            <value>
                <fullName>Nashville 030</fullName>
            </value>
            <value>
                <fullName>National Accounts 039</fullName>
            </value>
            <value>
                <fullName>South Bend 075</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chattanooga 035</fullName>
            </value>
            <value>
                <fullName>Cincinnati 065</fullName>
            </value>
            <value>
                <fullName>Elk Grove Village 085</fullName>
            </value>
            <value>
                <fullName>Evansville 050</fullName>
            </value>
            <value>
                <fullName>Fishers 055</fullName>
            </value>
            <value>
                <fullName>Fort Wayne 070</fullName>
            </value>
            <value>
                <fullName>Grand Rapids 080</fullName>
            </value>
            <value>
                <fullName>Johnson CIty 033</fullName>
                <label>Johnson City 033</label>
            </value>
            <value>
                <fullName>Knoxville 037</fullName>
            </value>
            <value>
                <fullName>Lexington 060</fullName>
            </value>
            <value>
                <fullName>Louisville 040</fullName>
            </value>
            <value>
                <fullName>Nashville 030</fullName>
            </value>
            <value>
                <fullName>National Accounts 039</fullName>
            </value>
            <value>
                <fullName>South Bend 075</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central Warehouse 038</fullName>
            </value>
            <value>
                <fullName>Chattanooga 035</fullName>
            </value>
            <value>
                <fullName>Cincinnati 065</fullName>
            </value>
            <value>
                <fullName>Elk Grove Village 085</fullName>
            </value>
            <value>
                <fullName>Evansville 050</fullName>
            </value>
            <value>
                <fullName>Fishers 055</fullName>
            </value>
            <value>
                <fullName>Fort Wayne 070</fullName>
            </value>
            <value>
                <fullName>Grand Rapids 080</fullName>
            </value>
            <value>
                <fullName>Johnson City 033</fullName>
            </value>
            <value>
                <fullName>Knoxville 037</fullName>
            </value>
            <value>
                <fullName>Lexington 060</fullName>
            </value>
            <value>
                <fullName>Louisville 040</fullName>
            </value>
            <value>
                <fullName>Nashville 030</fullName>
            </value>
            <value>
                <fullName>National Accounts 039</fullName>
            </value>
            <value>
                <fullName>South Bend 075</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Branch__c.field-meta.xml
<CustomField>
    <fullName>User_Branch__c</fullName>
    <label>User Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LTD_Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHelper.cls
public class CaseTriggerHelper {
    
     //Handler method for Insert
    public static void beforeInsertHandler(List<Case> cases,Map<Id,Case> oldcaseById){
        updateBranch(cases,null);
        updateCaseType(cases,null);
    }
    public static void beforeUpdateHandler(List<Case> cases,Map<Id,Case> oldcaseById){
        updateBranch(cases,oldcaseById);
        updateCaseType(cases,oldcaseById);
    }
    
    public static void updateBranch(List<Case> cases,Map<Id,Case> oldcaseById){
        //set to store owner Id 
        Set<Id> ownerIds = new Set<Id>();
        
        //Map to store a branch of particular user or Owner
        Map<Id,User> branchNameByOwnerId = null;
        
        //When record comes for update 
        // I will do check old opportunity Obj not null    
        //so if statement will execute
        if(oldcaseById != null){
            for(case cs : cases){
                if(cs.OwnerId != oldcaseById.get(cs.Id).OwnerId){
                    ownerIds.add(cs.OwnerId);    
                }
            } 
            
            // Record Comes for Insert 
            //so else statement will execute
        }else{
            for(case cs : cases){
                ownerIds.add(cs.OwnerId);  
            }
        }
        system.debug('ownerIds'+ownerIds);
        if(!ownerIds.isEmpty()){
            //Get USer Id And Its Related Opportunity Obj In Map
            branchNameByOwnerId = UserSelector.getUsersByUserIds(ownerIds);
            system.debug('branchNameByOwnerId'+branchNameByOwnerId);
            //Update the following Branch__c field 
            for(case cs : cases){
                if(branchNameByOwnerId.containsKey(cs.OwnerId)){
                    cs.Branch__c = branchNameByOwnerId.get(cs.OwnerId).User_Branch__c;
                }
            } 
        }
    }
   public static void updateCaseType(List<Case> cases,Map<Id,Case> oldcaseById){
        //system.debug('oldAccountById'+oldOpportunityById);
        //system.debug('accounts'+Opportunities);
        
        //set to store owner Id 
        Set<Id> accountIds = new Set<Id>();
        
        //Map to store a branch of particular Account
        Map<Id,Account> accountById = null;
        
        //When record comes for update 
        // I will do check old opportunity Obj not null    
        //so if statement will execute
        if(oldcaseById != null){
            for(case cs : cases){
                if(cs.AccountId != oldcaseById.get(cs.Id).AccountId){
                    accountIds.add(cs.AccountId);    
                }
            } 
            
            // Record Comes for Insert 
            //so else statement will execute
        }else{
            for(case cs : cases){
                accountIds.add(cs.AccountId);  
            }
        }
        system.debug('accountIds'+accountIds);
        if(!accountIds.isEmpty()){
            //Get USer Id And Its Related Opportunity Obj In Map
            accountById = AccountSelector.getAccountsByIds(accountIds);
            system.debug('accountById'+accountById);
            //Update the following Branch__c field 
            for(case cs : cases){
                if(accountById.containsKey(cs.AccountId)){
                    cs.Case_Type__c = accountById.get(cs.AccountId).Account_Category__c;
                }
            } 
        }
    }

}