force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <inlineHelpText>Which LTD Branch is this account associated with?</inlineHelpText>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central Warehouse 038</fullName>
            </value>
            <value>
                <fullName>Chattanooga 035</fullName>
            </value>
            <value>
                <fullName>Cincinnati 065</fullName>
            </value>
            <value>
                <fullName>Elk Grove Village 085</fullName>
            </value>
            <value>
                <fullName>Evansville 050</fullName>
            </value>
            <value>
                <fullName>Fishers 055</fullName>
            </value>
            <value>
                <fullName>Fort Wayne 070</fullName>
            </value>
            <value>
                <fullName>Grand Rapids 080</fullName>
            </value>
            <value>
                <fullName>Johnson City 033</fullName>
            </value>
            <value>
                <fullName>Knoxville 037</fullName>
            </value>
            <value>
                <fullName>Lexington 060</fullName>
            </value>
            <value>
                <fullName>Louisville 040</fullName>
            </value>
            <value>
                <fullName>Nashville 030</fullName>
            </value>
            <value>
                <fullName>National Accounts 039</fullName>
            </value>
            <value>
                <fullName>South Bend 075</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1 - Residential</fullName>
            </value>
            <value>
                <fullName>A2 - Commercial</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>D1</fullName>
            </value>
            <value>
                <fullName>D2</fullName>
            </value>
            <value>
                <fullName>D3</fullName>
            </value>
            <value>
                <fullName>D4</fullName>
            </value>
            <value>
                <fullName>E1 - Education</fullName>
            </value>
            <value>
                <fullName>G1 - Government</fullName>
            </value>
            <value>
                <fullName>GC1 - General Contractor</fullName>
            </value>
            <value>
                <fullName>H1 - Hospitality</fullName>
            </value>
            <value>
                <fullName>H2</fullName>
            </value>
            <value>
                <fullName>IC</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>M1 - Medical</fullName>
            </value>
            <value>
                <fullName>N1 - National Account</fullName>
            </value>
            <value>
                <fullName>POM - Property Owner / Manager</fullName>
            </value>
            <value>
                <fullName>RA1</fullName>
            </value>
            <value>
                <fullName>RA2</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>V1 - Tile Manufacturer</fullName>
            </value>
            <value>
                <fullName>V2 - Install Product Manufacturer</fullName>
            </value>
            <value>
                <fullName>V3 - IT / Data / Consultant</fullName>
            </value>
            <value>
                <fullName>V4 - Logistics Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Charge__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Charge__c</fullName>
    <label>Delivery Charge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_Via__c.field-meta.xml
<CustomField>
    <fullName>Ship_Via__c</fullName>
    <label>Ship Via</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LTL</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>WC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Account Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Central Warehouse 038</fullName>
            </value>
            <value>
                <fullName>Chattanooga 035</fullName>
            </value>
            <value>
                <fullName>Cincinnati 065</fullName>
            </value>
            <value>
                <fullName>Elk Grove Village 085</fullName>
            </value>
            <value>
                <fullName>Evansville 050</fullName>
            </value>
            <value>
                <fullName>Fishers 055</fullName>
            </value>
            <value>
                <fullName>Fort Wayne 070</fullName>
            </value>
            <value>
                <fullName>Grand Rapids 080</fullName>
            </value>
            <value>
                <fullName>Johnson City 033</fullName>
            </value>
            <value>
                <fullName>Knoxville 037</fullName>
            </value>
            <value>
                <fullName>Lexington 060</fullName>
            </value>
            <value>
                <fullName>Louisville 040</fullName>
            </value>
            <value>
                <fullName>Nashville 030</fullName>
            </value>
            <value>
                <fullName>National Accounts 039</fullName>
            </value>
            <value>
                <fullName>South Bend 075</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/send_creditApplication__c.field-meta.xml
<CustomField>
    <fullName>send_creditApplication__c</fullName>
    <defaultValue>false</defaultValue>
    <label>send creditApplication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/Credit_Application_Form__c.object-meta.xml
<CustomObject>
    <label>Credit Application Form</label>
    <nameField>
        <displayFormat>Credit Form-{000}</displayFormat>
        <label>Credit Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Applications Form</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Application_Form__c/fields/Application_Sent_By__c.field-meta.xml
<CustomField>
    <fullName>Application_Sent_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Sent By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Credit_Applications_Form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Submit For Approval</fullName>
            </value>
            <value>
                <fullName>Sent To Customer</fullName>
            </value>
            <value>
                <fullName>Opened By Customer</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Client Not Interested</fullName>
            </value>
            <value>
                <fullName>Assigned AR Specialist</fullName>
            </value>
            <value>
                <fullName>AR Review Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/BRANCH__c.field-meta.xml
<CustomField>
    <fullName>BRANCH__c</fullName>
    <label>BRANCH</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Credit Applications Form</relationshipLabel>
    <relationshipName>Credit_Applications_Form</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/CUSTOMER_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_TYPE__c</fullName>
    <label>CUSTOMER TYPE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/Delivery_Charge__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Charge__c</fullName>
    <label>Delivery Charge</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/PRICE_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRICE_CODE__c</fullName>
    <label>PRICE CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/SALESMAN__c.field-meta.xml
<CustomField>
    <fullName>SALESMAN__c</fullName>
    <label>SALESMAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/Ship_VIA__c.field-meta.xml
<CustomField>
    <fullName>Ship_VIA__c</fullName>
    <label>Ship VIA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <label>Stop</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application_Form__c/fields/Truck_Route__c.field-meta.xml
<CustomField>
    <fullName>Truck_Route__c</fullName>
    <label>Truck Route</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendCreditApplicationFormLinkController.cls
public class SendCreditApplicationFormLinkController {
    
    @auraEnabled
    public static ContactWrapper getContactNameAndEmail(Id contactID){
        List<Contact> contacts = ContactSelector.getContacts(new Set<Id>{contactID});
        if(contacts.isEmpty()){
            throw new AuraHandledException('No Contact Found.');
        }
        
        if(String.isBlank(contacts[0].Email)){
            throw new AuraHandledException('Email Address not found.');
        }
        
        try{
            
            //instance of contact wrapper
            ContactWrapper conWrap = new ContactWrapper();
            conWrap.creditApplication = new ApplicationWrapper();
            
            List<Credit_Application_Form__c> creditApplications = CreditApplicationFormSelector.getCreditApplications(new Set<Id>{contactID});
            // check form already exist or not
            if(!creditApplications.isEmpty()){
                conWrap.formExist = true;
                //get the application detail
                conWrap.creditApplication.creditApplicationId = creditApplications[0].Id;
                conWrap.creditApplication.branch = creditApplications[0].BRANCH__c;
                conWrap.creditApplication.priceCode = creditApplications[0].PRICE_CODE__c;
                conWrap.creditApplication.salesman = creditApplications[0].SALESMAN__c;
                conWrap.creditApplication.customerType = creditApplications[0].CUSTOMER_TYPE__c;
                conWrap.creditApplication.shipVia = creditApplications[0].Ship_VIA__c;
                conWrap.creditApplication.truckRoute = creditApplications[0].Truck_Route__c;
                conWrap.creditApplication.stop = creditApplications[0].Stop__c;
                conWrap.creditApplication.deliveryCharge = creditApplications[0].Delivery_Charge__c;
                conWrap.creditApplication.wareHouse = creditApplications[0].Warehouse__c;
                
            }
            
            for(Contact con: contacts){
                if(String.isBlank(con.FirstName)){
                    conWrap.contactName = con.LastName;
                }
                else{
                    conWrap.contactName = con.FirstName+' '+ con.LastName;
                }
                conWrap.email= con.Email;
                
            }
            return conWrap;
        }catch(Exception ex){
            ExceptionUtils.createExceptionLog('SendCreditApplicationFormLinkController - getContactNameAndEmail',ex.getMessage(),ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
        
    }
    
    
    @AuraEnabled
    public static void upsertCreditApplication(Id contactID, ApplicationWrapper creditAppWrapper){
        try{
            Credit_Application_Form__c creditApplication = new Credit_Application_Form__c();
            if(creditAppWrapper.creditApplicationId != null){
                creditApplication.Id = creditAppWrapper.creditApplicationId;
            }else{
                creditApplication.Contact__c = contactID;
                creditApplication.Application_Status__c = CreditApplicationContstants.Application_Status_Sent_To_Customer;
                creditApplication.Application_Sent_By__c = UserInfo.getUserId();// user which sending the email to customer
            }
            
            creditApplication.BRANCH__c = creditAppWrapper.branch;
            creditApplication.PRICE_CODE__c = creditAppWrapper.priceCode;
            creditApplication.SALESMAN__c = creditAppWrapper.salesman;
            creditApplication.CUSTOMER_TYPE__c = creditAppWrapper.customerType;
            creditApplication.Ship_VIA__c = creditAppWrapper.shipVia;
            creditApplication.Truck_Route__c = creditAppWrapper.truckRoute;
            creditApplication.Stop__c = creditAppWrapper.stop;
            creditApplication.Delivery_Charge__c = creditAppWrapper.deliveryCharge;
            creditApplication.Warehouse__c = creditAppWrapper.wareHouse;
            
            upsert creditApplication;
        }catch(Exception ex){
            ExceptionUtils.createExceptionLog('SendCreditApplicationFormLinkController - upsertCreditApplication',ex.getMessage(),ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
        
        
    }
    
    public class ContactWrapper{
        
        @AuraEnabled public string contactName {get; set;}
        @AuraEnabled public string email {get; set;}
        @AuraEnabled public boolean formExist {get; set;}
        @AuraEnabled public ApplicationWrapper creditApplication {get; set;}
        
        public ContactWrapper(){
            creditApplication = new ApplicationWrapper();
        }
    }
    
    
    public class ApplicationWrapper{
        @AuraEnabled public Id creditApplicationId {get; set;}
        @AuraEnabled public string branch {get; set;}
        @AuraEnabled public string priceCode {get; set;}
        @AuraEnabled public string salesman {get; set;}
        @AuraEnabled public string customerType {get; set;}
        @AuraEnabled public string shipVia {get; set;}
        @AuraEnabled public string truckRoute {get; set;}
        @AuraEnabled public string stop {get; set;}
        @AuraEnabled public string deliveryCharge {get; set;}
        @AuraEnabled public string wareHouse {get; set;}
    }
    
    
    
    @auraEnabled
    public static String sendEmailWithCreditApplicationFormLink(Id contactID){
        
        List<Contact> contacts = ContactSelector.getContacts(new Set<Id>{contactID});
        
        if(contacts.isEmpty()){
            throw new AuraHandledException('No Contact Found.');
        }
        
        if(String.isBlank(contacts[0].Email)){
            throw new AuraHandledException('Email Address not found.');
        }
        try{
            
            /*
            //call send email method
            if(!Test.isRunningTest()){
             Contact con=new Contact();
            con.send_creditApplication__c=true;
            con.Id=contactID;
            update con;   
            }
            */
           if(!Test.isRunningTest()) 
              sendEmail(contacts[0]);
            
            //return the contact Name
            return contacts[0].FirstName + ' ' + contacts[0].LastName;
        }catch(Exception ex){
            ExceptionUtils.createExceptionLog('SendCreditApplicationFormLinkController - sendEmailWithCreditApplicationFormLink',ex.getMessage(),ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }   
        
    }
    
    /***
* This method send the email based on salesforce contact email
*/ 
    public static void sendEmail(Contact con){
        // to get Owner name 
        User user = [SELECT Name, MobilePhone FROM User WHERE Id=:con.OwnerId];
        
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        //Set list of people who should get the email
        List<String> sendTo = new List<String>();
        
        sendTo.add(con.Email);
        mail.setToAddresses(sendTo);
        
        //Set email content
        mail.setSubject('Credit Application Form');
        String body = 'Hello ' + (String.isBlank( con.FirstName) ? '' :  (con.FirstName + ' ')) + con.LastName + ', ';
        body += '<br/>'; 
        body += 'Thank you for your interest in opening a credit account with Louisville Tile! ';
        body += 'Please follow the link below to complete our application. It is important to complete all sections of the application so that your information can be reviewed and processed in a timely manner.';
        body += ' Please also make sure to read all terms and conditions of the account and sign where indicated by an officer of the company.';
        body += '<br/>';
        body += '<br/>'; 
        body += 'If you are exempt from sales tax, please provide a copy of your certificate(s) with application.'; 
        body += '<br/>';
        body += '<br/>'; 
        body += 'We look forward to doing business with you, and should you have any questions regarding the status of your application, please contact' +' '+ user.MobilePhone + '';
        body += '<br/>'; 
        body += '<br/>';
        body += '<a href='+''+System.Label.Credit_Application_Form_URL+''+'?contactid='+ con.Id +'>Click Here</a>'+' '+' to open the credit application form';
        body += '<br/>'; 
        body += '<br/>'; 
        body += 'Sincerely,';
        
        
        mail.setHtmlBody(body);
        
        //Add your email to the master list
        mails.add(mail);
       
        
        //Send all emails in the master list
        try{
            if(!Test.isRunningTest())
                Messaging.sendEmail(mails);
        }catch(Exception ex){
            
            ExceptionUtils.createExceptionLog('SendCreditApplicationFormLinkController - sendEmail',ex.getMessage(),ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
        
    }
    
}