force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1 - Residential</fullName>
            </value>
            <value>
                <fullName>A2 - Commercial</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>D1</fullName>
            </value>
            <value>
                <fullName>D2</fullName>
            </value>
            <value>
                <fullName>D3</fullName>
            </value>
            <value>
                <fullName>D4</fullName>
            </value>
            <value>
                <fullName>E1 - Education</fullName>
            </value>
            <value>
                <fullName>G1 - Government</fullName>
            </value>
            <value>
                <fullName>GC1 - General Contractor</fullName>
            </value>
            <value>
                <fullName>H1 - Hospitality</fullName>
            </value>
            <value>
                <fullName>H2</fullName>
            </value>
            <value>
                <fullName>IC</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>M1 - Medical</fullName>
            </value>
            <value>
                <fullName>N1 - National Account</fullName>
            </value>
            <value>
                <fullName>POM - Property Owner / Manager</fullName>
            </value>
            <value>
                <fullName>RA1</fullName>
            </value>
            <value>
                <fullName>RA2</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>V1 - Tile Manufacturer</fullName>
            </value>
            <value>
                <fullName>V2 - Install Product Manufacturer</fullName>
            </value>
            <value>
                <fullName>V3 - IT / Data / Consultant</fullName>
            </value>
            <value>
                <fullName>V4 - Logistics Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Professional.recordType-meta.xml
<RecordType>
    <fullName>Professional</fullName>
    <active>true</active>
    <description>Select to create professional type account.</description>
    <label>Professional</label>
</RecordType>

force-app/main/default/objects/Dealer_Customer__c/Dealer_Customer__c.object-meta.xml
<CustomObject>
    <label>Dealer Customer</label>
    <nameField>
        <displayFormat>Dealer Customer-{0000}</displayFormat>
        <label>Dealer Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Customers</relationshipLabel>
    <relationshipName>Dealer_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer_Customer__c/fields/Sales_And_Market__c.field-meta.xml
<CustomField>
    <fullName>Sales_And_Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales And Market</label>
    <referenceTo>Sales_And_Market__c</referenceTo>
    <relationshipLabel>Dealer Customers</relationshipLabel>
    <relationshipName>Dealer_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Display_Item__c/Display_Item__c.object-meta.xml
<CustomObject>
    <label>Display Item</label>
    <nameField>
        <displayFormat>Display Item - {0000}</displayFormat>
        <label>Display Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Display Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Display_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Display Items</relationshipLabel>
    <relationshipName>Display_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Display_Item__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Display_Item__c/fields/SalesandMarket__c.field-meta.xml
<CustomField>
    <fullName>SalesandMarket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales And Market</label>
    <referenceTo>Sales_And_Market__c</referenceTo>
    <relationshipLabel>Display Items</relationshipLabel>
    <relationshipName>Display_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Display_Item__c/fields/Style_Type__c.field-meta.xml
<CustomField>
    <fullName>Style_Type__c</fullName>
    <label>Style Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Display_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ceramic Tile</fullName>
            </value>
            <value>
                <fullName>Ancillary Items</fullName>
            </value>
            <value>
                <fullName>LVT</fullName>
            </value>
            <value>
                <fullName>Laminate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Display_Item__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Display_Item__c/fields/Why_is_the_Dealer_using_products__c.field-meta.xml
<CustomField>
    <fullName>Why_is_the_Dealer_using_products__c</fullName>
    <label>Why is the Dealer using products?</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/Sales_And_Market__c.object-meta.xml
<CustomObject>
    <label>Dealer Profile</label>
    <nameField>
        <label>Sales And Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_And_Market__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_And_Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Ancillary_Purchases_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ancillary_Purchases_Percentage__c</fullName>
    <label>Ancillary Purchases(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Annual_Tile_Ancillary_Purchases_Per__c.field-meta.xml
<CustomField>
    <fullName>Annual_Tile_Ancillary_Purchases_Per__c</fullName>
    <label>Annual Tile + Ancillary Purchases (%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Annual_Tile_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Annual_Tile_Sales_Percentage__c</fullName>
    <label>Annual Tile Sales (%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Assumed_Annual_Purchases_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Assumed_Annual_Purchases_Percentage__c</fullName>
    <label>Assumed Annual Purchases(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Created_year__c.field-meta.xml
<CustomField>
    <fullName>Created_year__c</fullName>
    <label>Created year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Ancillary_Sales_Market_Share__c.field-meta.xml
<CustomField>
    <fullName>LTD_Ancillary_Sales_Market_Share__c</fullName>
    <label>LTD Ancillary Sales Market Share</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/ltd_Ancillary_Sales_MST__c.field-meta.xml
<CustomField>
    <fullName>ltd_Ancillary_Sales_MST__c</fullName>
    <label>LTD Ancillary Sales MST</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Ancillary_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>LTD_Ancillary_Sales_Percentage__c</fullName>
    <label>LTD Ancillary Sales(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Ancillary_Sales_Market_Share__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Ancillary_Sales_Market_Share__c</fullName>
    <label>LTD Tile + Ancillary Sales Market Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Ancillary_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Ancillary_Sales_Percentage__c</fullName>
    <label>LTD Tile + Ancillary Sales(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/ltd_Tile_And_Ancillary_Sales_MST__c.field-meta.xml
<CustomField>
    <fullName>ltd_Tile_And_Ancillary_Sales_MST__c</fullName>
    <label>LTD Tile And Ancillary Sales MST</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/ltd_Tile_Sales_Market_MST__c.field-meta.xml
<CustomField>
    <fullName>ltd_Tile_Sales_Market_MST__c</fullName>
    <label>LTD Tile Sales Market MST</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Sales_Market_Share__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Sales_Market_Share__c</fullName>
    <label>LTD Tile Sales Market Share</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Sales_Percentage__c</fullName>
    <label>LTD Tile Sales(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Tile_Purchases_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Tile_Purchases_Percentage__c</fullName>
    <label>Tile Purchases(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Total_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Revenue__c</fullName>
    <label>Total Annual Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Total_Annual_Revenue_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Revenue_Percentage__c</fullName>
    <label>Total Annual Revenue(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/DealerProfileControllerTest.cls
@isTest
public class DealerProfileControllerTest {
    @testSetup static void setup(){
        Id recId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
        Account acc = new Account();
        acc.RecordTypeId = recId;
        acc.Name = 'Test';
        acc.Phone = '9911255555';
        acc.Fax = '12231231231';
        insert acc;
        
        
        
        
        Sales_And_Market__c dealerProfileSalesAndMarket = new Sales_And_Market__c();
        dealerProfileSalesAndMarket.Account__c = acc.Id;
        dealerProfileSalesAndMarket.Total_Annual_Revenue__c = 234;
        dealerProfileSalesAndMarket.Created_year__c = '2023';
        dealerProfileSalesAndMarket.LTD_Ancillary_Sales_Market_Share__c = 33;
        dealerProfileSalesAndMarket.Annual_Tile_Ancillary_Purchases_Per__c = 40;
        dealerProfileSalesAndMarket.Annual_Tile_Sales_Percentage__c = 45;
        dealerProfileSalesAndMarket.Assumed_Annual_Purchases_Percentage__c = 25;
        dealerProfileSalesAndMarket.LTD_Ancillary_Sales_Market_Share__c = 29;
        dealerProfileSalesAndMarket.ltd_Ancillary_Sales_MST__c = 35;
        dealerProfileSalesAndMarket.LTD_Ancillary_Sales_Percentage__c = 45;
        dealerProfileSalesAndMarket.LTD_Tile_Ancillary_Sales_Market_Share__c = 40;
        dealerProfileSalesAndMarket.LTD_Tile_Ancillary_Sales_Percentage__c = 35;
        dealerProfileSalesAndMarket.ltd_Tile_And_Ancillary_Sales_MST__c = 45;
        dealerProfileSalesAndMarket.ltd_Tile_Sales_Market_MST__c = 54;
        dealerProfileSalesAndMarket.LTD_Tile_Sales_Market_Share__c = 43;
        dealerProfileSalesAndMarket.LTD_Tile_Sales_Percentage__c = 32;
        dealerProfileSalesAndMarket.Tile_Purchases_Percentage__c = 33;
        dealerProfileSalesAndMarket.Total_Annual_Revenue_Percentage__c = 65;
        dealerProfileSalesAndMarket.Ancillary_Purchases_Percentage__c = 25;
        Insert dealerProfileSalesAndMarket;
        
        Dealer_Customer__c dcustomer=new Dealer_Customer__c();
        dcustomer.Customer_Name__c='Test';
        dcustomer.Account__c=acc.Id;
        dcustomer.Sales_And_Market__c=dealerProfileSalesAndMarket.Id;
        insert dcustomer;
        
        Display_Item__c displayItem = new Display_Item__c();
        displayItem.Account__c =acc.id;
        displayItem.Price__c = 100;
        displayItem.Style_Type__c = 'Test supply type';
        displayItem.Supplier__c = 'Test Supplier';
        displayItem.SalesandMarket__c = dealerProfileSalesAndMarket.id;
        displayItem.Type__c = 'LVT';
        displayItem.Volume__c = 200.0;
        displayItem.Why_is_the_Dealer_using_products__c = 'TEst Why_is_the_Dealer_using_products__c';
        insert displayItem;
        
        Display_Item__c dc=new Display_Item__c();
        dc.Supplier__c='Home';
        dc.Manufacturer__c='manu';
        dc.Account__c=acc.id;
        insert dc;
        
    }
    
    @isTest static void getMetaDataRecordsTest(){
        test.startTest();
        Map<String,String> mapNalueByName = DealerProfileController.getMetaDataRecords();
        test.stopTest();
    }
    @isTest static void fetchOnLoadConfigrationTest(){
        Id AccountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        test.startTest();
        Map<String,List<String>> mapNalueByName = DealerProfileController.fetchOnLoadConfigration(AccountId);
        test.stopTest();  
    }
    @isTest static void getAccountsByIdTest(){
        Id AccountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        test.startTest();
        List<Account> listAccount = DealerProfileController.getAccountsById(AccountId);
        test.stopTest();   
    }
    @isTest static void getAllDealerProfilesTest(){
        Id AccountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        
        test.startTest();
        List<Sales_And_Market__c> listSalesAndMarket = DealerProfileController.getAllDealerProfiles(AccountId);
        test.stopTest();   
    }
    @isTest static void getDealerProfileRecordTest(){
        
        Id AccountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        Id salesId = [Select Id,Created_year__c from Sales_And_Market__c where Created_year__c = '2023' limit 1].Id;
        String selectedYear = '2023';
        Dealer_Customer__c dc=new Dealer_Customer__c();
        dc.Account__c=AccountId;
        dc.Customer_Name__c='name';
        dc.Inactive__c=true;
        dc.Customer_Type__c='Dealer';
        dc.Selections__c='Home';
        dc.Sales_And_Market__c=salesId;
        insert dc;
        test.startTest();
        DealerProfileController.getDealerProfileRecord(selectedYear,AccountId);
        test.stopTest();   
    }
    @isTest static void saveDisplayItemsTest(){
        Id AccountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        DealerProfileController.DisplayItemWrapper displayItem = new DealerProfileController.DisplayItemWrapper();
        DealerProfileController.DisplayItemByType displayItemByType = new DealerProfileController.DisplayItemByType();
        DisplayItemByType.dealerType='Ancillary Items';
        DisplayItemByType.manufacturer='Test Manufacturer';
        DisplayItemByType.price = 12.0;
        DisplayItemByType.Supplier = 'Test Supplier';
        DisplayItemByType.isChange = true;
        DisplayItemByType.isDeleted = false;
        displayItem.displayItemByTypeDetails.add(DisplayItemByType);
        
        test.startTest();
        DealerProfileController.saveDisplayItems(JSON.serialize(displayItem),AccountId);
        test.stopTest();   
    }
    @isTest static void saveDisplayItemsTest2(){
        Id AccountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        Id displayitemid = [Select Id from Display_Item__c where Manufacturer__c = 'manu' limit 1].Id;
        DealerProfileController.DisplayItemWrapper displayItem = new DealerProfileController.DisplayItemWrapper();
        DealerProfileController.DisplayItemByType displayItemByType = new DealerProfileController.DisplayItemByType();
        DisplayItemByType.dealerType='Ancillary Items';
        DisplayItemByType.manufacturer='Test Manufacturer';
        DisplayItemByType.price = 12.0;
        DisplayItemByType.ids=displayitemid;
        DisplayItemByType.Supplier = 'Test Supplier';
        DisplayItemByType.isChange = true;
        DisplayItemByType.isDeleted = false;
        displayItem.displayItemByTypeDetails.add(DisplayItemByType);
        
        test.startTest();
        DealerProfileController.saveDisplayItems(JSON.serialize(displayItem),AccountId);
        test.stopTest();   
    }
    
    
    @isTest static void getDisplayItemTest(){
        Id accountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        string displayItemType = 'LVT';
        string currentYear = '2022';
        test.startTest();
        DealerProfileController.getDisplayItem(displayItemType,currentYear,accountId);
        test.stopTest();
    }
    
    @isTest static void getAccountDetailsTest(){
        Id accountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        test.startTest();
        DealerProfileController.getAccountDetails(accountId);
        test.stopTest();
    }
    
    @isTest static void getRecordByYearTest(){
        Id accountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        string selectedYear = [Select Id,Account__c,Created_year__c from Sales_And_Market__c where Account__c = :accountId limit 1].Created_year__c;
        test.startTest();
        integer salesAndMarketCount = DealerProfileController.getRecordByYear(selectedYear,accountId);
        test.stopTest();
        system.assertEquals(1, salesAndMarketCount);
    }
    @istest
    public static void saveDealerProfileRecordTest(){
        Id AccountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
        Id dealerCustomerId = [Select Id,Name from Dealer_Customer__c where Customer_Name__c = 'Test' limit 1].Id;
        DealerProfileController.DealerProfileWrapper objdealerProfileWrapper =new DealerProfileController.DealerProfileWrapper();
        objdealerProfileWrapper.dealerName='Test';
        objdealerProfileWrapper.ltdAncillarySalesMarketShareTarget=100;
        objdealerProfileWrapper.ltdTileSalesMarketShareTarget=100;
        objdealerProfileWrapper.ltdTileAndAncillarySalesMarketShareTarget=100;
        objdealerProfileWrapper.dealerAnnualSalesTotal=100;
        objdealerProfileWrapper.createdYear='2022';
        objdealerProfileWrapper.dealerAnnualSalesTotalPercentage=100;
        objdealerProfileWrapper.dealerAnnualPurchase=100;
        objdealerProfileWrapper.dealerAnnualPurchasePercentage=100;
        objdealerProfileWrapper.dealerAnnualTileSaleincludelabour=100;
        objdealerProfileWrapper.dealerAnnualTileSaleincludelabourPercentage=100;
        objdealerProfileWrapper.dealerAnnualPurchase=100;
        objdealerProfileWrapper.ancillaryPurchases=100;
        objdealerProfileWrapper.ancillaryPurchasesPercentage=100;
        objdealerProfileWrapper.dealerAnnualTileandAnnualPurchase=100;	
        objdealerProfileWrapper.dealerAnnualTileandAnnualPurchasePercentage=100;
        objdealerProfileWrapper.tilePurchase=100;
        objdealerProfileWrapper.tilePurchasePercentage=100;
        objdealerProfileWrapper.ltdTileAndAncillarySales=100;
        objdealerProfileWrapper.ltdTileAndAncillarySalesPercentage=100;
        objdealerProfileWrapper.ltdTileSale=100;
        objdealerProfileWrapper.ltdTileSalePercentage=100;
        objdealerProfileWrapper.ltdAncillarySales=100;
        objdealerProfileWrapper.ltdAncillarySalesPercentage=100;
        objdealerProfileWrapper.ltdTileAndAncillarySalesMarketShare=100;
        objdealerProfileWrapper.ltdTileSalesMarketShare=100;
        objdealerProfileWrapper.ltdAncillarySalesMarketShare=100;  
        List <DealerProfileController.DealerCustomerDetailsWrapper> dcd=new List<DealerProfileController.DealerCustomerDetailsWrapper>();
        for(Integer i=1;i<10;i++){
            DealerProfileController.DealerCustomerDetailsWrapper dcWrap=new DealerProfileController.DealerCustomerDetailsWrapper();
            dcWrap.customerName='customerName'+i;
            dcWrap.customerType='Dealer';
            dcWrap.salesperson='salesperson';
            dcWrap.supplier='supplier';
            dcWrap.inactive=true;
            dcWrap.dealerCustomerId=dealerCustomerId;
            dcd.add(dcWrap);
            
        }
        objdealerProfileWrapper.dealerCustomerDetails=dcd;    
        test.startTest();
        DealerProfileController.saveDealerProfileRecord(JSON.serialize(objdealerProfileWrapper),AccountId);
        test.stopTest();
        
    }
    
    /*  @istest
public static void saveDealerProfileRecordTest2(){
Id AccountId = [Select Id,Name from Account where Name = 'Test' limit 1].Id;
Sales_And_Market__c salesId = [Select id from Sales_And_Market__c where Created_year__c = '2023' limit 1];
DealerProfileController.DealerProfileWrapper  dealerProfile=new DealerProfileController.DealerProfileWrapper();
DealerProfileController.DealerCustomerDetailsWrapper dealerCustomer=new DealerProfileController.DealerCustomerDetailsWrapper();

dealerProfile.dealerAnnualSalesTotal=100;
dealerProfile.ltdTileSale=109;


dealerProfile.ltdAncillarySales=343;
test.startTest();
DealerProfileController.saveDealerProfileRecord(JSON.serialize(salesId),AccountId);
test.stopTest();

}*/
    
    
}