force-app/main/default/objects/Account/fields/Preferred_vendor__c.field-meta.xml
<CustomField>
    <fullName>Preferred_vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred vendor</label>
    <referenceTo>Preferred_vendor__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Current_Account__c/Current_Account__c.object-meta.xml
<CustomObject>
    <label>Current Account</label>
    <nameField>
        <label>Current Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Current Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Current_Account__c/fields/Current_Account_City__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_City__c</fullName>
    <label>Current Account City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Current_Account__c/fields/Current_Account_Purchase_Volume__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_Purchase_Volume__c</fullName>
    <label>Current Account Purchase Volume</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Current_Account__c/fields/Current_Account_Remark__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_Remark__c</fullName>
    <label>Current Account Remark</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Current_Account__c/fields/Current_Account_State__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_State__c</fullName>
    <label>Current Account State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatesName</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Current_Account__c/fields/Current_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_Type__c</fullName>
    <label>Current Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Residential Dealer</fullName>
            </value>
            <value>
                <fullName>Commercial Dealer</fullName>
            </value>
            <value>
                <fullName>Big Box</fullName>
            </value>
            <value>
                <fullName>Flooring Contractor</fullName>
            </value>
            <value>
                <fullName>Design Showroom</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Current_Account__c/fields/Current_Length_of_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Length_of_Relationship__c</fullName>
    <label>Current Length of Relationship</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Current_Account__c/fields/Preferred_vendor__c.field-meta.xml
<CustomField>
    <fullName>Preferred_vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred vendor</label>
    <referenceTo>Preferred_vendor__c</referenceTo>
    <relationshipLabel>Current Accounts</relationshipLabel>
    <relationshipName>Current_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Preferred_vendor__c/Preferred_vendor__c.object-meta.xml
<CustomObject>
    <label>Preferred vendor</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Preferred vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CurrentAccountSelector.cls
public class CurrentAccountSelector {
	/**
     * This method return the CurrentAccount fields name
     */ 
    public static List<String> getCurrentAccountFields(){
        return new List<String>{
                                	'Name',
                                	'Current_Account_City__c',
                                	'Current_Account_Purchase_Volume__c',
                                	'Current_Account_Remark__c',
                                	'Current_Account_State__c',
                                    'Current_Account_Type__c',
                                     'Current_Length_of_Relationship__c'
                               };
    }
    
    /**
     * This method return the Current Account record if ids matched
     */ 
     public static List<Current_Account__c> getCurrentAccounts(Set<Id> preferredVendorIDs){
        String query = 'SELECT Id, ' + String.join( getCurrentAccountFields(), ', ' ) + ' FROM Current_Account__c WHERE Preferred_vendor__c IN :preferredVendorIDs';
        return database.query(query);
    }
    
}