force-app/main/default/objects/Kerridge_Quote__c/Kerridge_Quote__c.object-meta.xml
<CustomObject>
    <label>Kerridge Quote</label>
    <nameField>
        <label>Kerridge Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kerridge Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kerridge_Quote__c/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <label>Expiration date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Kerridge_Quote__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Id</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Kerridge Quotes</relationshipLabel>
    <relationshipName>Kerridge_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Creator_Name__c.field-meta.xml
<CustomField>
    <fullName>Creator_Name__c</fullName>
    <label>Creator Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estimated_Cost_per_Location__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Cost_per_Location__c</fullName>
    <label>Estimated Sales per Location</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Inactive_Product_Alert__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Product_Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactive Product Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NA_Project__c.field-meta.xml
<CustomField>
    <fullName>NA_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NA Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>National Account Build</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>National Account Project</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_ID_for_Kerridge__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID_for_Kerridge__c</fullName>
    <displayFormat>OPP-{0000000}</displayFormat>
    <externalId>true</externalId>
    <label>Opportunity ID for Kerridge</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Alternate Project Name(s)</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Registration__c.field-meta.xml
<CustomField>
    <fullName>Project_Registration__c</fullName>
    <label>Project Registration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Submitted to Vendor</fullName>
            </value>
            <value>
                <fullName>Reviewed/Finalized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <label>Quote Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Register_Job_Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Register_Job_Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Register Job Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Dealer_Builder.recordType-meta.xml
<RecordType>
    <fullName>Dealer_Builder</fullName>
    <active>true</active>
    <businessProcess>Dealer%2FBuilder Sales Process</businessProcess>
    <label>Dealer/Builder</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/National_Account_Build.recordType-meta.xml
<RecordType>
    <fullName>National_Account_Build</fullName>
    <active>true</active>
    <businessProcess>National  Account Build Sales Process</businessProcess>
    <label>National Account Build</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/National_Account_Project_Opportunities.recordType-meta.xml
<RecordType>
    <fullName>National_Account_Project_Opportunities</fullName>
    <active>true</active>
    <businessProcess>National Account Sales Process</businessProcess>
    <label>National Account Project</label>
</RecordType>

force-app/main/default/objects/Project_Bidders__c/Project_Bidders__c.object-meta.xml
<CustomObject>
    <description>Used to associate multiple &quot;account&quot; objects, or bidders, with projects, or opportunities.</description>
    <label>Project Bidder</label>
    <nameField>
        <displayFormat>Bidder-{000000}</displayFormat>
        <label>Project Bidders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Bidders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Bidders__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Bidders</relationshipLabel>
    <relationshipName>Project_Bidders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Bidders__c/fields/Winning_Bidder__c.field-meta.xml
<CustomField>
    <fullName>Winning_Bidder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Winning Bidder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Selection_Sheet__c/Selection_Sheet__c.object-meta.xml
<CustomObject>
    <label>Selection Sheet</label>
    <nameField>
        <label>Selection Sheet #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selection Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Selection_Sheet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Selection Sheets</relationshipLabel>
    <relationshipName>Selection_Sheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Selection_Sheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Inquiry/Planning</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Finalized</fullName>
                <isActive>false</isActive>
                <label>Finalized</label>
            </value>
            <value>
                <fullName>Inquiry - Planning</fullName>
                <isActive>false</isActive>
                <label>Inquiry - Planning</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>On Order</fullName>
                <isActive>false</isActive>
                <label>On Order</label>
            </value>
            <value>
                <fullName>Partial Order</fullName>
                <isActive>false</isActive>
                <label>Partial Order</label>
            </value>
            <value>
                <fullName>nquiry - Planning</fullName>
                <isActive>false</isActive>
                <label>nquiry - Planning</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunitySelector.cls
public class OpportunitySelector {
    
    public static List<Opportunity> getOpportunitiesById(Set<Id> ids){
        return [Select Id,NA_Project__c,AccountId,Inactive_Product_Alert__c,OwnerId,Name,Opportunity_ID_for_Kerridge__c,
                	Creator_Name__c,Amount,Opportunity.owner.Name,Owner.Email,
                	Project_Name__c,City__c,State__c,CloseDate,StageName,
                	Estimated_Cost_per_Location__c,Project_Registration__c,
                	Register_Job_Send_Email__c,RecordType.id	
                From Opportunity 
                Where Id IN:ids];
    }
    
    public static List<Opportunity> getOpportunitiesByIdAndDeveloperName(Set<Id> ids){
        return [Select Id,Estimated_Cost_per_Location__c From Opportunity 
                Where Id IN:ids 
                AND (RecordType.DeveloperName='National_Account_Project_Opportunities' OR RecordType.DeveloperName='Dealer_Builder')];
    }
    
    public static List<AggregateResult> getTotalNoOfOpportunitiesByNAProject(Set<Id> ids){
        return [SELECT NA_Project__c,Count(Id)countId,Sum(Amount) totalAmount FROM Opportunity 
                where NA_Project__c IN:ids 
                GROUP BY NA_Project__c];
    }
    
    public static Map<Id,Opportunity> getOpportunityByNAProject(Set<Id> ids){
        return new Map<Id,Opportunity>([SELECT Id,Name,
                                        NA_Project__c 
                                        FROM Opportunity 
                                        WHERE NA_Project__c IN:ids]);
    }    
    
    public static list<Opportunity> getOpportunityByAccountAndRecordType(Set<Id> ids,String recordType){
        return [Select Id,Name,Amount 
                FROM Opportunity 
                WHERE AccountId IN:ids 
                AND RecordType.DeveloperName=:recordType];
        
    }
    
    public static Map<Id,Opportunity> getOpportunityWithProjectBidderById(Set<Id> ids){
        return new Map<Id,Opportunity>( [SELECT id,StageName,
                                         	(SELECT Id 
                                             FROM Project_Bidders__r 
                                             WHERE Winning_Bidder__c=true )
                                         FROM opportunity 
                                         WHERE Id IN: ids] );
    }
       
    public static List<Opportunity> getOpportunitiesByIdsAndRecordType(Set<Id> ids,Id commericalRecordTypeId, Id naBuildRecordTypeId){
        return [SELECT Id FROM Opportunity WHERE Id IN:ids
                AND (RecordTypeId=:commericalRecordTypeId OR RecordTypeId=:naBuildRecordTypeId)];
    }
    
    public static List<Opportunity> getOpportunitiesByIdsAndRecordId(Set<Id> ids,Id RecordTypeId){
        return [SELECT Id,RecordTypeId,Pricebook2Id
                FROM Opportunity 
                WHERE Id IN:ids 
                AND RecordTypeId=:recordTypeId];
    }
    
    public static List<Opportunity> getOpportunitiesAndSelectionSheetByIdsAndRecordId(Set<Id> ids,Id RecordTypeId){
        return [SELECT id,StageName,CloseDate,
                	(SELECT id,Status__c 
                     FROM Selection_Sheets__r) 
                FROM Opportunity 
                WHERE Id IN: ids 
                AND RecordTypeId=:recordTypeId];
    }
    
    public static List<Opportunity> getOpportunitiesAndKerridgeQuotesByIdsAndRecordType(Set<Id> ids){
        return [SELECT Id,Quote_Status__c,
                	(SELECT Id,Opportunity_Id__c,Expiration_date__c 
                     FROM Kerridge_Quotes__r) 
                FROM Opportunity 
                WHERE Id IN:ids
                AND RecordType.DeveloperName !='National_Account_Build'];
    }
    
    public static List<Opportunity> getOpportunityCreatedInMonthByUser(){
        Date startOfMonth = Date.today().toStartOfMonth();
        Date startOfNextMonth = startOfMonth.addMonths(1);
        return [SELECT Id, Name 
                        FROM Opportunity 
                        WHERE ownerid =:userinfo.getuserid()  AND CreatedDate >= :startOfMonth AND CreatedDate < :startOfNextMonth];
    }
    public static List<Opportunity> getOpportunityCreatedInYearByUser(){
        return [SELECT Id, Name 
                        FROM Opportunity
                        WHERE ownerid =:userinfo.getuserid()  AND CreatedDate >= LAST_N_DAYS:365];
    }
      public static List<Opportunity> getOpportunitiesByAccountIds(Set<Id> ids){
        return [Select Id,NA_Project__c,AccountId,Inactive_Product_Alert__c,OwnerId,Name,Opportunity_ID_for_Kerridge__c,
                	Creator_Name__c,Amount,Opportunity.owner.Name,Owner.Email,
                	Project_Name__c,City__c,State__c,CloseDate,StageName,
                	Estimated_Cost_per_Location__c,Project_Registration__c,
                	Register_Job_Send_Email__c	
                From Opportunity 
                Where AccountId IN:ids];
    }
}