force-app/main/default/objects/Opportunity/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <businessProcess>Commercial Sales Process</businessProcess>
    <label>Test - Admin Use Only</label>
</RecordType>

force-app/main/default/objects/Project_Bidders__c/Project_Bidders__c.object-meta.xml
<CustomObject>
    <description>Used to associate multiple &quot;account&quot; objects, or bidders, with projects, or opportunities.</description>
    <label>Project Bidder</label>
    <nameField>
        <displayFormat>Bidder-{000000}</displayFormat>
        <label>Project Bidders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Bidders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Bidders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects Bid</relationshipLabel>
    <relationshipName>Project_Bidders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Bidders__c/fields/Bidder_Involvement_Date__c.field-meta.xml
<CustomField>
    <fullName>Bidder_Involvement_Date__c</fullName>
    <label>Bidder Involvement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Bidders__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Bidders</relationshipLabel>
    <relationshipName>Project_Bidders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Bidders__c/fields/Winning_Bidder__c.field-meta.xml
<CustomField>
    <fullName>Winning_Bidder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Winning Bidder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHelperTest.cls
@isTest
private class AccountTriggerHelperTest {
    
    @isTest
    private static void isAfterUpdateHandlerTest(){
        Map<Id,Account> newMapAccountById =new Map<Id,Account>();
        Map<Id,Account> oldMapAccountById= new Map<Id,Account>();
        
        String random = String.valueof(DateTime.now().getTime());
        Profile profile = [SELECT Id FROM Profile WHERE Name='Sales Representative - Residential'];
        User user = new User();
        user.Email = 'random@random.com'+random;
        user.UserName = 'admin@random.com'+random;
        user.LastName = 'random'+random;
        user.Alias = 'random';
        user.ProfileId = profile.Id;
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey = 'America/Los_Angeles';
        insert user;
        
        Account acc=new Account();
        acc.Name='testing';
        insert acc;
       
        Account acc1=new Account();
        acc1.Name='testing';
        insert acc1;
        oldMapAccountById.put(acc1.Id,acc1);
        
        Opportunity opp=new Opportunity();
        opp.Name='new Opportunity';
        opp.AccountId=acc.Id;
        opp.CloseDate=date.today();
        opp.StageName='Design & Planning';
        insert opp;
        
        Project_Bidders__c pbidder=new Project_Bidders__c();
        pbidder.Opportunity__c=opp.Id;
        pbidder.Account__c=acc1.Id;
        pbidder.Bidder_Involvement_Date__c=date.today();
        insert pbidder;
        Project_Bidders__c pbs=[select id,Winning_Bidder__c from Project_Bidders__c where id =:pbidder.Id];
        pbs.Winning_Bidder__c=true;
        update pbs;
        Account ac=[select id,OwnerId from Account where id=:oldMapAccountById.keyset()];
        ac.OwnerId=user.Id;
        newMapAccountById.put(ac.Id,ac);
        test.startTest();
            AccountTriggerHelper.isAfterUpdateHandler(oldMapAccountById,newMapAccountById);
            test.stopTest();
    }
}