force-app/main/default/objects/Dealer_Customer__c/Dealer_Customer__c.object-meta.xml
<CustomObject>
    <label>Dealer Customer</label>
    <nameField>
        <displayFormat>Dealer Customer-{0000}</displayFormat>
        <label>Dealer Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Customers</relationshipLabel>
    <relationshipName>Dealer_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer_Customer__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Bucket &amp; Trowel</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Commercial Contractor</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Interior design</fullName>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath</fullName>
            </value>
            <value>
                <fullName>National Account</fullName>
            </value>
            <value>
                <fullName>Property owner</fullName>
            </value>
            <value>
                <fullName>Residential Contractor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Retail</fullName>
                <isActive>false</isActive>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer_Customer__c/fields/Sales_And_Market__c.field-meta.xml
<CustomField>
    <fullName>Sales_And_Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales And Market</label>
    <referenceTo>Sales_And_Market__c</referenceTo>
    <relationshipLabel>Dealer Customers</relationshipLabel>
    <relationshipName>Dealer_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer_Customer__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <label>Sales Person</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_Customer__c/fields/Selections__c.field-meta.xml
<CustomField>
    <fullName>Selections__c</fullName>
    <label>Selections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dealer Showroom</fullName>
            </value>
            <value>
                <fullName>Builder Showroom</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/Sales_And_Market__c.object-meta.xml
<CustomObject>
    <label>Dealer Profile</label>
    <nameField>
        <label>Sales And Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_And_Market__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_And_Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Ancillary_Purchases__c.field-meta.xml
<CustomField>
    <fullName>Ancillary_Purchases__c</fullName>
    <label>Ancillary Purchases</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Ancillary_Purchases_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ancillary_Purchases_Percentage__c</fullName>
    <label>Ancillary Purchases(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Annual_Tile_Ancillary_Purchases__c.field-meta.xml
<CustomField>
    <fullName>Annual_Tile_Ancillary_Purchases__c</fullName>
    <label>Annual Tile + Ancillary Purchases</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Annual_Tile_Ancillary_Purchases_Per__c.field-meta.xml
<CustomField>
    <fullName>Annual_Tile_Ancillary_Purchases_Per__c</fullName>
    <label>Annual Tile + Ancillary Purchases (%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Annual_Tile_Sales_Include_labor__c.field-meta.xml
<CustomField>
    <fullName>Annual_Tile_Sales_Include_labor__c</fullName>
    <label>Annual Tile Sales (Include labor)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Annual_Tile_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Annual_Tile_Sales_Percentage__c</fullName>
    <label>Annual Tile Sales (%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Assumed_Annual_Purchases__c.field-meta.xml
<CustomField>
    <fullName>Assumed_Annual_Purchases__c</fullName>
    <label>Assumed Annual Purchases</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Assumed_Annual_Purchases_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Assumed_Annual_Purchases_Percentage__c</fullName>
    <label>Assumed Annual Purchases(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Created_year__c.field-meta.xml
<CustomField>
    <fullName>Created_year__c</fullName>
    <label>Created year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Ancillary_Sales__c.field-meta.xml
<CustomField>
    <fullName>LTD_Ancillary_Sales__c</fullName>
    <label>LTD Ancillary Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Ancillary_Sales_Market_Share__c.field-meta.xml
<CustomField>
    <fullName>LTD_Ancillary_Sales_Market_Share__c</fullName>
    <label>LTD Ancillary Sales Market Share</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/ltd_Ancillary_Sales_MST__c.field-meta.xml
<CustomField>
    <fullName>ltd_Ancillary_Sales_MST__c</fullName>
    <label>LTD Ancillary Sales MST</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Ancillary_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>LTD_Ancillary_Sales_Percentage__c</fullName>
    <label>LTD Ancillary Sales(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Ancillary_Sales__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Ancillary_Sales__c</fullName>
    <label>LTD Tile + Ancillary Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Ancillary_Sales_Market_Share__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Ancillary_Sales_Market_Share__c</fullName>
    <label>LTD Tile + Ancillary Sales Market Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Ancillary_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Ancillary_Sales_Percentage__c</fullName>
    <label>LTD Tile + Ancillary Sales(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/ltd_Tile_And_Ancillary_Sales_MST__c.field-meta.xml
<CustomField>
    <fullName>ltd_Tile_And_Ancillary_Sales_MST__c</fullName>
    <label>LTD Tile And Ancillary Sales MST</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Sales__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Sales__c</fullName>
    <label>LTD Tile Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/ltd_Tile_Sales_Market_MST__c.field-meta.xml
<CustomField>
    <fullName>ltd_Tile_Sales_Market_MST__c</fullName>
    <label>LTD Tile Sales Market MST</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Sales_Market_Share__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Sales_Market_Share__c</fullName>
    <label>LTD Tile Sales Market Share</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/LTD_Tile_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>LTD_Tile_Sales_Percentage__c</fullName>
    <label>LTD Tile Sales(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Tile_Purchases__c.field-meta.xml
<CustomField>
    <fullName>Tile_Purchases__c</fullName>
    <label>Tile Purchases</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Tile_Purchases_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Tile_Purchases_Percentage__c</fullName>
    <label>Tile Purchases(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Total_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Revenue__c</fullName>
    <label>Total Annual Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/fields/Total_Annual_Revenue_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Revenue_Percentage__c</fullName>
    <label>Total Annual Revenue(%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/SalesAndMarketSelector.cls
public class SalesAndMarketSelector {
    
    public static List<Sales_And_Market__c> getAllDealerProfile(Set<Id> accountIds){
        
        return [Select Id,Name,Created_year__c,CreatedDate,LastModifiedDate from Sales_And_Market__c where Account__c IN:accountIds order by Created_year__c];
        
    }
    public static List<Sales_And_Market__c> getSalesAndMarketByAccountIdAndCeatedYear(set<Id> accountIds,String selectedYear){
        return [select Id,Name,Ancillary_Purchases__c,CreatedDate,Created_year__c,ltd_Ancillary_Sales_MST__c,ltd_Tile_Sales_Market_MST__c,ltd_Tile_And_Ancillary_Sales_MST__c,	Ancillary_Purchases_Percentage__c, 
                Annual_Tile_Ancillary_Purchases__c,Annual_Tile_Ancillary_Purchases_Per__c,Annual_Tile_Sales_Percentage__c,Annual_Tile_Sales_Include_labor__c,
                                            Assumed_Annual_Purchases__c,Assumed_Annual_Purchases_Percentage__c,LTD_Ancillary_Sales__c,LTD_Ancillary_Sales_Percentage__c,
                                            LTD_Tile_Ancillary_Sales__c,LTD_Tile_Ancillary_Sales_Percentage__c,LTD_Tile_Sales__c,LTD_Tile_Sales_Percentage__c,
                                            Tile_Purchases__c,Tile_Purchases_Percentage__c,Total_Annual_Revenue__c,Total_Annual_Revenue_Percentage__c,LTD_Tile_Sales_Market_Share__c,LTD_Tile_Ancillary_Sales_Market_Share__c,LTD_Ancillary_Sales_Market_Share__c,(select Id,Name,Customer_Type__c,Customer_Name__c,Inactive__c,Notes__c,Sales_Person__c,Selections__c,Supplier__c from Dealer_Customers__r)
                from Sales_And_Market__c where Account__c IN: accountIds AND Created_year__c=:selectedYear];
    }

}