force-app/main/default/objects/Dealer_Customer__c/Dealer_Customer__c.object-meta.xml
<CustomObject>
    <label>Dealer Customer</label>
    <nameField>
        <displayFormat>Dealer Customer-{0000}</displayFormat>
        <label>Dealer Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Customer__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Bucket &amp; Trowel</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Commercial Contractor</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Interior design</fullName>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath</fullName>
            </value>
            <value>
                <fullName>National Account</fullName>
            </value>
            <value>
                <fullName>Property owner</fullName>
            </value>
            <value>
                <fullName>Residential Contractor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Retail</fullName>
                <isActive>false</isActive>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer_Customer__c/fields/Sales_And_Market__c.field-meta.xml
<CustomField>
    <fullName>Sales_And_Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales And Market</label>
    <referenceTo>Sales_And_Market__c</referenceTo>
    <relationshipLabel>Dealer Customers</relationshipLabel>
    <relationshipName>Dealer_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer_Customer__c/fields/Selections__c.field-meta.xml
<CustomField>
    <fullName>Selections__c</fullName>
    <label>Selections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dealer Showroom</fullName>
            </value>
            <value>
                <fullName>Builder Showroom</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_And_Market__c/Sales_And_Market__c.object-meta.xml
<CustomObject>
    <label>Dealer Profile</label>
    <nameField>
        <label>Sales And Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_And_Market__c/fields/Created_year__c.field-meta.xml
<CustomField>
    <fullName>Created_year__c</fullName>
    <label>Created year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DealerProfileFetchOnloadConfigration.cls
public class DealerProfileFetchOnloadConfigration {
    
     //picklist values
	public Map<String,List<String>> getPickListValues(){
        Map<String, List<String>> picklistValuesByFieldName = new Map<String, list<String>>();
        List<String> getDealerCustomerTypeValue = new List<String>();
        List<String> getSelections= new List<String>();
        List<String> getCreatedYear= new List<String>();
        Schema.DescribeFieldResult dealerCustomerTypefieldResult = Dealer_Customer__c.Customer_Type__c.getDescribe();
        List<Schema.PicklistEntry> dealerCustomerTypeValues = dealerCustomerTypefieldResult.getPicklistValues();
        for (Schema.PicklistEntry ac: dealerCustomerTypeValues) {
            getDealerCustomerTypeValue.add(ac.getValue());
        }
        picklistValuesByFieldName.put('accountCategory',new list<string>(getDealerCustomerTypeValue));
        
        Schema.DescribeFieldResult selectionsfieldResult = Dealer_Customer__c.Selections__c.getDescribe();
        List<Schema.PicklistEntry> selectionsValues = selectionsfieldResult.getPicklistValues();
        for (Schema.PicklistEntry sel: selectionsValues) {
            getSelections.add(sel.getValue());
        }
         picklistValuesByFieldName.put('selections',new list<string>(getSelections));
        
        Schema.DescribeFieldResult selectionsfieldResultforYear = Sales_And_Market__c.Created_year__c.getDescribe();
        List<Schema.PicklistEntry> selectionsValuesforYear = selectionsfieldResultforYear.getPicklistValues();
        for (Schema.PicklistEntry sel: selectionsValuesforYear) {
            getCreatedYear.add(sel.getValue());
        }
        picklistValuesByFieldName.put('createdYear',new list<string>(getCreatedYear));
         return picklistValuesByFieldName;
}
}